version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 737346429178

phases:
  pre_build:
    commands:
      - echo "Logging into ECR.."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
  build_image:
    commands:
      - echo "Building image.."
      - docker build -t clm-training .
      - docker tag sf-intrabot:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/clm-training:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/clm-training:latest
